language: c
compiler: clang
install:
    - sudo apt-get install libsdl1.2-dev libsdl1.2debian
    - wget 'http://downloads.sourceforge.net/project/sdl-draw/SDL_draw/1.2.13/SDL_draw-1.2.13.tar.gz' -O sdl_draw.tar.gz
    - tar -xzf sdl_draw.tar.gz
    - cd SDL_draw-1.2.13/
    - ./configure --prefix=/usr/local/
    - make && sudo make install
    - sudo cp -f include/SDL_draw.h /usr/include/SDL
    - cd ..
    - wget 'http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2' -O cunit.tar.bz2
    - tar -xjf cunit.tar.bz2
    - cd CUnit-2.1-2/
    - ./configure --prefix=/usr/local/
    - make && sudo make install
    - sudo ldconfig
    - cd ..
script: ./gradlew clean release_build runTests
notifications:
    on_success: never
    on_failure: always
env:
    global:
        - TERM=dumb
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        - PATH=$PATH:/usr/local/lib
