language: c
compiler: clang
install: gradle clean injectLibs snapshotNjgrSharedLibrary installSnapshotTestExecutable runTests
notifications:
    on_success: never
    on_failure: always
env:
    global:
        - TERM=dumb
